# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aae83e52575b205987bfbd38345c1ca3310294f22c7fd921051c0fbef860049c14afaabdfc8259965a3ec1edcc685e2aa48bb497d624be54627dfcfff7373d7e

test:
  secret_key_base: 8c47220ba6e5be11bceda3b397a19118d2f335097f5d1a009235c1d11e46f8badc728b9836e98c46f28063b2b1755a0df3796d8e8701a7c50bc5ac7dc96caa82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
